### ISSUE TITLE
go get failed.

### ISSUE THREAD

**Issue by donnol** [gencebay/httplive#1]
When I go get github.com/gencebay/httplive, it failed with:

    # github.com/gencebay/httplive/lib
    go/src/github.com/gencebay/httplive/lib/controller.go:106:13: c.ShouldBindJSON undefined (type 
    *gin.Context has no field or method ShouldBindJSON)
    go/src/github.com/gencebay/httplive/lib/controller.go:122:13: c.ShouldBindJSON undefined (type 
    *gin.Context has no field or method ShouldBindJSON)

**Comment by lndj** [comment]
+1

**Comment by aimof** [comment]
`c.ShouldBindJson` method was added 3 months ago.
I guess your gin repo is old one.

## case your gin repo is old.

```shell
# in $GOPATH/src/github.com/gin-gonic/gin
$ git reset --hard b8b6831
HEAD is now at b8b6831 feat: add multiple service example. (#1119)
$ go get github.com/gencebay/httplive
# github.com/gencebay/httplive/lib
../../gencebay/httplive/lib/controller.go:106:13: c.ShouldBindJSON undefined (type *gin.Context has no field or method ShouldBindJSON)
../../gencebay/httplive/lib/controller.go:122:13: c.ShouldBindJSON undefined (type *gin.Context has no field or method ShouldBindJSON)
```

## to solve

You can do this.

```shell
go get -u github.com/gencebay/httplive
```

If you do this command, your gin repo is updated and you can go get httplive.  (This command may cause a dependency problem)

**Comment by playmyswift** [comment]
+1

**Comment by donnol** [comment]
It work. Thanks. @aimof
