### ISSUE TITLE
Editor Autosave not working

### ISSUE THREAD

**Issue by frank-west-iii** [gencebay/httplive#8]
The editor is not autosaving when making changes to the response json. I can create, edit, and delete endpoints. I just can't change the response body.

There are no errors in the console, but there are a couple of warnings.

```
jsoneditor.min.js:30 Unknown option "enableBasicAutocompletion". This option will be ignored
jsoneditor.min.js:30 Unknown option "savingProgress". This option will be ignored
jsoneditor.min.js:30 Unknown option "enableBasicAutocompletion". This option will be ignored
jsoneditor.min.js:30 Unknown option "savingProgress". This option will be ignored
```

I can post the full stack trace if needed.

```
go version go1.9.2 darwin/amd64
httplive version 0.0.1
```

I'm starting to dig into the code, but just wanted to see if there was anything familiar with this problem.

**Comment by gencebay** [comment]
please can you try Cmd+S for Mac or Ctrl+S for Windows PC. I will check that out

**Comment by frank-west-iii** [comment]
lol.. thanks. I didn't even try that. I thought it was an auto-save. That works just fine.
